print('Type-1')
for i in range(5):  #range(0 -inclusive to 5 -exclusive)
    print(i)
print('Type-2')
for i in range(1,10):  #range(1 -inclusive to 10 -exclusive)
    print(i)
print('Type-3')
for i in range(1,20,2): #range(1 -inclusive to 20 -exclusive, with a step of -2)
    print(i)